### PR TITLE
Add sprockets precompile rake task

### LINKED ISSUE #189: Slow to generate application.js
When I launch smashing, the first request takes around 30 seconds. It looks like this is when it generates application.js. 

Is this normal and expected, and if so are there any known ways to cache and/or speed this up. Restarting the server to re-read jobs scripts makes development slow. I realise I could move jobs out of smashing and have them push data in via the API, but wanted to check first others experiences.

Running Ubuntu 18 on Jetson Xavier NX

### PR DESCRIPTION
**Pull request by kinow**
Closes #189 

To test:

1. copy file into a dashboards project (we assume `bundle install` etc has run, the dashboard is running fine)
2. `rake precompile-assets`
3. confirm `assets/javascripts/application.js` was created
4. start your dashboard, make sure widgets, jobs, etc, are all working
5. enjoy! :tada:

### CODE REVIEW

**Comment by qume** [comment]
Ok so this runs, and generates application.js which looks sensible. However the page just shows the background and no widgets.

In the console it says "Yeah! The dashboard has started!", and that's it.

The generated application.js is here: https://termbin.com/oaolz

I tried diffing the precompiled one with the live one, but diff choked (I guess doesn't like the long minified lines). Doing a manual look through they seem identical. When I fetch the live generated one with curl and name it application.js - same problem, just a gray background with no widgets.

Probably something really simple I'm missing here but a bit stumped. There are no errors logged to the console or 404's etc.

**Comment by kinow** [comment]
@qume is there any chance you used the old `Rakefile`? I had the same result with the previous `Rakefile` as that was missing the sassc/sass and coffee-script imports. But after adding them, the generated `application.js` worked fine.

**Comment by qume** [comment]
Awesome my bad I didn't copy over the new Rakefile from the template directory in the gem. 

It works. Thank you!!

**Comment by kinow** [comment]
Excellent news @qume ! Thanks for testing it! I'll merge it, and wait a few more days/weeks to see if we get any other gem updates, issues, improvements, etc. A new version should be released in the next weeks with this `Rakefile`. I'll update documentation too. Cheers, Bruno.

**Comment by kinow** [comment]
Change log updated. Milestone updated. Docs added too to sidebar with a link to this new wiki page: https://github.com/Smashing/smashing/wiki/How-to%3A-precompile-assets

**Pull request merged**
